### ISSUE TITLE
ROS2 Documentation

### ISSUE THREAD

**Issue by yashveerjain** [PegasusSimulator/PegasusSimulator#20]
I'm eager to use ROS 2 with Isaac Sim and Pegasus, but haven't found any official guides to get started. Px4 Mavlink seems to be the default integration, but are there resources available for using ROS 2 with Pegasus?  Currently, I only see Px4 options within the Isaac Sim panel.
Thanks in advance.

**Comment by MarceloJacinto** [comment]
I still need to write the documentation on that part. I have a script for running with ROS 2 in the examples folder (https://github.com/PegasusSimulator/PegasusSimulator/blob/main/examples/3_ros2_single_vehicle.py) 

No GUI available for that yet, as it had a bug in the previous Isaac Sim version, so I ended up disabling the ROS2 button.  However, the functionality is still there

**Comment by yashveerjain** [comment]
First of all great work! and thanks for the update. I am able to run standalone python script, and works great. I'll keep look out for ros2 updates. 
Thanks again.
