### ISSUE TITLE
Could not connect with the ROS2

### ISSUE THREAD

**Issue by ricardo907** [PegasusSimulator/PegasusSimulator#21]
![截图 2024-04-08 01-06-51](https://github.com/PegasusSimulator/PegasusSimulator/assets/116164217/8c82f984-e02e-4864-b0df-4f130f48a716)

Hello, When I use the UAV , the streaming Backend is only have PX4? Could you help me to solve it ?

**Comment by MarceloJacinto** [comment]
Try to run the following example:
`ISAACSIM_PYTHON examples/3_ros2_single_vehicle.py`

[https://github.com/PegasusSimulator/PegasusSimulator/blob/main/examples/3_ros2_single_vehicle.py](https://github.com/PegasusSimulator/PegasusSimulator/blob/main/examples/3_ros2_single_vehicle.py)

**Comment by 261963130** [comment]
Hello, I'm currently using isaacsim version 4.5, I'm not sure if this version is compatible with your drone simulator or if you will follow up with a compatible version!
