### ISSUE TITLE
Isaac Sim 4.0.0 Support

### ISSUE THREAD

**Issue by ramzibou0735** [PegasusSimulator/PegasusSimulator#41]
Wondering if Isaac Sim 4.0.0 is in the works and if we'll be able to use Isaac Lab tools with Pegasus

**Comment by MarceloJacinto** [comment]
I'm working on it. Check the branch [dev_isaac_4](https://github.com/PegasusSimulator/PegasusSimulator/tree/dev_isaac_4).
