### ISSUE TITLE
GPS coordinate mapping to issac sim coordinates.

### ISSUE THREAD

**Issue by shashisingh** [PegasusSimulator/PegasusSimulator#47]
First of all, thanks for the work put in to create the simulator. I have been trying to run examples and also trying to understand how different components interact with each other. My use case is to create an outdoor scene and process images are they are being captured by the USD camera in Issac-Sim.  

I sometimes notice errors (drone is stuck on the same frame forever, altitude errors etc.) while flying the simulator through QGroundControl. I am trying to debug these cases. As part of this, I wanted to trace how GPS co-ordinates on QGroundControl map are being mapped to the coordinate space of Issac-Sim scene.  If I want the drone to move towards an object in the scene, how would that be mapped to GPS location on QGroundControl? Thank you for any help.

**Comment by fyl1991** [comment]
In this link [link](https://pegasussimulator.github.io/PegasusSimulator/source/features/environments.html#setting-the-map-global-coordinates) for the description of gps information, I hope it will be helpful to you.

**Comment by MarceloJacinto** [comment]
I will recommend for you to take a closer look at the [Conference Paper](https://ieeexplore.ieee.org/document/10556959), section III-D (sensor modeling) - the math behind the GPS projection is there. You can also change the coordinates of the center of the projection by following the link suggested by @fyl1991.

The code for the GPS implementation is [here](https://github.com/PegasusSimulator/PegasusSimulator/blob/main/extensions/pegasus.simulator/pegasus/simulator/logic/sensors/gps.py).

Hope this helps.
