### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'initialize_simulation_context_async'

### ISSUE THREAD

**Issue by kokoory** [PegasusSimulator/PegasusSimulator#53]
Hello, Thanks for your work!

After installing, I could run sim and control using qgc. but I have updated kernel and other things, I am facing an error. 
Nvidia driver and ISAAC version is the same as written on the web.

I could running ISAACSIM, after clicking 'load vehicle' , I've got this error.

Thanks for your help!
------------------------------------------
[Error] [asyncio] Task exception was never retrieved
future: <Task finished name='Task-189' coro=<UIDelegate.on_load_vehicle.<locals>.async_load_vehicle() done, defined at /home/den/Documents/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/ui/ui_delegate.py:177> exception=AttributeError("'NoneType' object has no attribute 'initialize_simulation_context_async'")>
Traceback (most recent call last):
  File "/home/den/Documents/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/ui/ui_delegate.py", line 183, in async_load_vehicle
    await self._pegasus_sim.world.initialize_simulation_context_async()
AttributeError: 'NoneType' object has no attribute 'initialize_simulation_context_async'
-----------------------------------------

**Comment by TannerGilbert** [comment]
You have to load a scence by clicking "Load Scene" in the scene selector before trying to spawn the vehicle as else the `world` will be `None`.

![Scence Selector](https://github.com/user-attachments/assets/b65a526d-332f-47fd-a3d5-6f6a2d14eab1)

**Comment by MarceloJacinto** [comment]
Thank you @TannerGilbert for providing the support. This is the correct answer. I will be closing the issue.
